### ISSUE TITLE
job  dynamic define

### ISSUE THREAD

**Issue by lxiaoixi** [hokify/agenda#17]
I use pm2 start 4 process, and I  create job by http request, and I define job when create job, but  this job only define the current process.  when job start, if another process get this job lock,  but don't define job,  the job will execute fail。

So I want to know  is job can dynamic define?

I want to listen start event, then I define job , but I find origin code get definition before emit start event, So if there hava a prefer way？

```
 this.on('start', async (job: any) => {
            if(!this.definitions[job.attrs.name]){
                this.define(job.attrs.name, this.jobHandler); 
            }
}
```

```
       const definition = this.agenda.definitions[this.attrs.name];
        this.attrs.lastRunAt = new Date();
        log('[%s:%s] setting lastRunAt to: %s', this.attrs.name, this.attrs._id, this.attrs.lastRunAt.toISOString());
        this.computeNextRunAt();
        await this.save();
        try {
            this.agenda.emit('start', this);
            this.agenda.emit(`start:${this.attrs.name}`, this);
            log('[%s:%s] starting job', this.attrs.name, this.attrs._id);
            if (!definition) {
                log('[%s:%s] has no definition, can not run', this.attrs.name, this.attrs._id);
                throw new Error('Undefined job');
            }
```
As above， If the definition  can declaration after  this.agenda.emit('start', this) ?

**Comment by simllll** [comment]
Interesting question, dynamic job defintions are currently not supported. I'm intereseted in your use case? I'm kinda afraid this is not so easy possible, and not quite sure if this is actually something we should allow in general, as dynamic job defintions could be pretty hard to maintain.

**Comment by lxiaoixi** [comment]
> Interesting question, dynamic job defintions are currently not supported. I'm intereseted in your use case? I'm kinda afraid this is not so easy possible, and not quite sure if this is actually something we should allow in general, as dynamic job defintions could be pretty hard to maintain.
> 
> You can always add custom job data though? Could this solve your issue? E.g. by defining one job processor with "do whatever I like you to do" and job data says: "mode: xyz"...

As above, my case is I create  a  new job, when I define job, it only define in one process, I want to sync it in other process。but now I have to query db to sync it。

You say I can only define one job processor,  but  Does it  mean that  all jobs name is same?

**Comment by simllll** [comment]
Yes, all the jobs will have the same name, but that's the more appropiate way to deal with this. You always can use the "data" property for your needs, e.g. if you like to sort or show other names for the job, just pick it from the data property.
