### ISSUE TITLE
[FEATURE REQUEST] Graceful shutdown support

### ISSUE THREAD

**Issue by mhemrg** [hokify/agenda#21]
Hi.
What you've done in this fork is so awesome. Keep up the good work.

I think this fork doesn't support the `stop` method yet.
https://github.com/agenda/agenda#stop

Do you think adding it to this fork would require a lot of effort?

**Comment by simllll** [comment]
Hi @mhemrg , thanks for your report.
.stop() is implemented and inlcudes even some fixes ;-):
see here https://github.com/hokify/agenda/blob/a359fe3489e4424bdb186eee0be607fc481c4e2d/src/index.ts#L511

I will close the issue, if I understand you wrong, please feel free to open it again!
